# Generated by Django 4.0.2 on 2024-03-02 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewepisode',
            name='isfavorite',
        ),
        migrations.RemoveField(
            model_name='reviewmaster',
            name='isfavorite',
        ),
        migrations.RemoveField(
            model_name='reviewversion',
            name='isfavorite',
        ),
    ]
