# Generated by Django 4.0.2 on 2024-02-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComicMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('author', models.CharField(max_length=100, verbose_name='作者')),
                ('era', models.CharField(choices=[('1980', '1980'), ('1990', '1990'), ('2000', '2000'), ('2010', '2010')], max_length=100, verbose_name='年代')),
                ('publisher', models.CharField(choices=[('enikkisu', 'エニックス'), ('gakushu', '学習研究科'), ('shogakukan', '小学館'), ('shonengaho', '少年画報社'), ('tokuma', '徳間書店'), ('asahi', '朝日ソラノマ'), ('tokyo', '東京三世社'), ('hakusen', '白泉社'), ('akita', '秋田書店'), ('takeshobo', '竹書房'), ('hobun', '芳文社'), ('kadokawa', '角川書店'), ('kodan', '講談社'), ('shuei', '集英社')], max_length=100, verbose_name='出版社')),
                ('target', models.CharField(choices=[('girl', '少女'), ('boy', '少年'), ('woman', '女性'), ('man', '男性')], max_length=100, verbose_name='対象')),
                ('genre', models.CharField(choices=[('four-panel', '4コマ'), ('sf', 'SF'), ('gag', 'ギャグ'), ('suspense', 'サスペンス'), ('sport', 'スポーツ'), ('battle', 'バトル'), ('fantasy', 'ファンタジー'), ('horor', 'ホラー'), ('lovecome', 'ラブコメ'), ('animal', '動物'), ('love', '恋愛'), ('history', '時代劇')], max_length=100, verbose_name='ジャンル')),
                ('cover', models.ImageField(blank=True, upload_to='cover/')),
            ],
        ),
    ]
