# Generated by Django 4.0.2 on 2024-03-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comicmaster',
            name='genre',
            field=models.CharField(choices=[('4コマ', '4コマ'), ('SF', 'SF'), ('ギャグ', 'ギャグ'), ('サスペンス', 'サスペンス'), ('スポーツ', 'スポーツ'), ('バトル', 'バトル'), ('ファンタジー', 'ファンタジー'), ('ホラー', 'ホラー'), ('ラブコメ', 'ラブコメ'), ('動物', '動物'), ('恋愛', '恋愛'), ('時代劇', '時代劇')], max_length=100, verbose_name='ジャンル'),
        ),
        migrations.AlterField(
            model_name='comicmaster',
            name='publisher',
            field=models.CharField(choices=[('エニックス', 'エニックス'), ('学習研究科', '学習研究科'), ('小学館', '小学館'), ('少年画報社', '少年画報社'), ('徳間書店', '徳間書店'), ('朝日ソラノマ', '朝日ソラノマ'), ('東京三世社', '東京三世社'), ('白泉社', '白泉社'), ('秋田書店', '秋田書店'), ('竹書房', '竹書房'), ('芳文社', '芳文社'), ('角川書店', '角川書店'), ('講談社', '講談社'), ('集英社', '集英社')], max_length=100, verbose_name='出版社'),
        ),
        migrations.AlterField(
            model_name='comicmaster',
            name='target',
            field=models.CharField(choices=[('少女', '少女'), ('少年', '少年'), ('女性', '女性'), ('男性', '男性')], max_length=100, verbose_name='対象'),
        ),
    ]
