# Generated by Django 4.0.2 on 2024-02-20 17:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0003_alter_comicversion_version_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comicversion',
            name='version_number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='巻数'),
        ),
    ]
