# Generated by Django 4.0.2 on 2024-02-20 17:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0004_alter_comicversion_version_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComicEpisode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('episode_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='エピソード数')),
                ('cover', models.ImageField(blank=True, upload_to='cover/episode/')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comics.comicmaster')),
                ('version_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comics.comicversion')),
            ],
            options={
                'verbose_name_plural': 'エピソード',
            },
        ),
    ]
