# Generated by Django 4.0.2 on 2024-02-20 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0005_comicepisode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comicepisode',
            old_name='version_number',
            new_name='title_version',
        ),
        migrations.RemoveField(
            model_name='comicepisode',
            name='title',
        ),
    ]
